### ISSUE TITLE
Submit Race Setup issues

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#17]
Doesn't seem to allow you to submit a race setup - or it is allowing it, but there's no obvious confirmation that this is allowed?

Would be ideal if the issues with e.g. gear/braking numbers being higher/lower than allowed showed up in a red box like they do in qualifying and it specified what was missing.

NB - the minimum required to submit a Race Setup is:

**EITHER all Dry Corners with a Gear/Braking value OR all Wet Corners with a Gear/Braking value** (would be great to put out a warning message if one isn't filled out that says "You have not put in any values for a Dry/Wet setup.  This means if the weather is Dry/Wet that you will crash out of the race."   Clearly, delete Dry/Wet according to what has/hasn't been included and I've said "crash out of the race" but I can't actually remember what we said would happen in that instance!  If it's just losing loads of time then change it to be accurate please :)
**Starting Fuel Amount** (Minimum should be 10 litres - maximum should be 180 litres)

It would be good to add a message to say "You have not added any pit-stops yet - if you run out of fuel/tyres, you will lose a huge amount of time on track!" or words to that effect.

**Comment by christopherh0rn** [comment]
This is now done, going to move this to be a feature request because none of the "it would be nice/great/good to have" have been implemented.
The requested validation should all be in place though.

**Comment by JonBeagles** [comment]
Not obvious when the player presses 'Submit Race Setup' that it has actually been submitted?  Would be good if it could display a message that says "Race Setup now submitted" when they click submit (presuming it's successful).

**Comment by JonBeagles** [comment]
""Having filled in the Dry, Wet and Pit Stops tabs I cannot submit race setup.
When I try I get a "Please submit a complete race setup for at least one weather" error message."

Another from the UAT - big issue this one!  NB - this is all from Test Driver #3 so far.

**Comment by JonBeagles** [comment]
"I went back through the race sheet and submitted successfully this time, not sure why it worked this time?

There is no indication that the race setup has been submitted successfully, perhaps a 'Submitted' message or something to indicate that it has gone through would be helpful?

Once you log out and then back in the race setup info is not retained/shown to the manager so you cannot see what was submitted. None of the dry or wet setups, or the stint info is shown on the Race Setup page tabs."

Intriguingly going back out and back in did allow for a race submission - and without any prompting they also agree with wanting a 'Submitted' type message FYI.  Retaining what info was submitted would also be great to have.

**Comment by JonBeagles** [comment]
Also would be ideal to be able to see who has/has not submitted a race setup.  Means I can send out reminders (either manually, or perhaps an auto-triggered email within the system in future) accordingly.

**Comment by christopherh0rn** [comment]
Just for clarity, I've moved the bug portion of this to a separate issue so it doesn't get lost in the multiple feature requests.
The bug is #30

**Comment by christopherh0rn** [comment]
Perhaps also for clarity, in future you could open a new issue for each separate feature request as again, it's very easy to lose track of things in long comment threads!

**Comment by christopherh0rn** [comment]
> Also would be ideal to be able to see who has/has not submitted a race setup. Means I can send out reminders (either manually, or perhaps an auto-triggered email within the system in future) accordingly.

Opened a separate feature request for this here #34

**Comment by christopherh0rn** [comment]
> Doesn't seem to allow you to submit a race setup - or it is allowing it, but there's no obvious confirmation that this is allowed?
> 
> Would be ideal if the issues with e.g. gear/braking numbers being higher/lower than allowed showed up in a red box like they do in qualifying and it specified what was missing.
> 
> NB - the minimum required to submit a Race Setup is:
> 
> **EITHER all Dry Corners with a Gear/Braking value OR all Wet Corners with a Gear/Braking value** (would be great to put out a warning message if one isn't filled out that says "You have not put in any values for a Dry/Wet setup. This means if the weather is Dry/Wet that you will crash out of the race." Clearly, delete Dry/Wet according to what has/hasn't been included and I've said "crash out of the race" but I can't actually remember what we said would happen in that instance! If it's just losing loads of time then change it to be accurate please :)
> **Starting Fuel Amount** (Minimum should be 10 litres - maximum should be 180 litres)
> 
> It would be good to add a message to say "You have not added any pit-stops yet - if you run out of fuel/tyres, you will lose a huge amount of time on track!" or words to that effect.

Opened a separate feature request #35 for messages on submission with missing (non-compulsory) data

**Comment by christopherh0rn** [comment]
Opened a separate feature request for confirmation on successful submission #39
Think that is all the feature requests separated out from this thread so closing now.
