### ISSUE TITLE
3 x issues

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#2]
Hey bro,

So - and this may be deliberate and very clever - but if I try to run a lap with 1st gear in every corner and with braking at or above 22.5m (tried 22.9, 23, 25, 30, 40, 50, 80, 90, 100, 998 and 999) it won't let me run the lap.  If that is because that is such a poor lap that it will produce a huge lap-time (which it would), then I don't necessarily mind that...but it would be good if a message could come up, rather than just nothing happening.

Though if there is an issue where in any track/any corner you can't input more than 22.5m then that's clearly a problem that needs fixing...!

Another issue is that Lap 1 is showing as having 0 fuel use or tyre wear?  The Lap 2 fuel/tyres look VERY low...I thought I had put in a normal amount, but I can't work out how to see what I put in there - that would be useful in future to be able to go back and see what parameters I had included.  I don't think I would have used something so low though, so can you check that is calculating correctly please?

Final issue I have found is that - after setting the qualifying session to finish at 20:30, I have just been able to run a lap at 20:40 with a relatively normal set-up.  That should not have been possible given when the session finishes:

"Indy - Test
2021-06-05 20:12:00 - 2021-06-05 20:30:00"

Also, things to look at for future:

1 - Colours for the feedback (e.g. Perfect being Gold, Amazing being Green etc. - ideally Fast would be red and Blue would be slow...but need to work out exactly how that would all work!  Open to any suggestions you have on that)
2 - F1R logo (I can email it you) appearing large on the log-in screen/small on most other screens would be really cool.
3 - Would be epic if I could assign images to each player for e.g. the driver/car they are in that showed up somewhere in qualifying (in the space at the left or right hand side of the screen perhaps).
4 - Site background changing from white to something a little more visually appealing would be good.

Clearly none of those 4 are huge issues compared to the previous ones listed above and the fact that you can't submit a race setup right now!

Cheers,
Jon

**Comment by christopherh0rn** [comment]
If you could split this into 3 issues (well 7 with the future improvements!) that would be great.

1st gear with high braking isn't working because it is producing a total slow time loss greater than 999.9999999999 which is the max, I will add a couple more digits onto that, that aught to cover it (ie 99,999.9... total slow time loss)

**Comment by JonBeagles** [comment]
Closed that now and opened up new ones (apart from the one you already responded to).
________________________________
