### ISSUE TITLE
Time Left?

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#20]
For some reason the time left doesn't seem to be coming down after running laps?

![image](https://user-images.githubusercontent.com/85413662/123874649-6882eb00-d930-11eb-84f2-5ccb61020378.png)

I ran 1 lap (as you can see here):

![image](https://user-images.githubusercontent.com/85413662/123874694-77699d80-d930-11eb-9baf-e65a88afcd1d.png)

But no amends to the time on track or time left values?

**Comment by JonBeagles** [comment]
NB - did show up when I refreshed, which coincided with the session ended.

**Comment by christopherh0rn** [comment]
As you discovered this doesn't currently update until you refresh, will make it update without refresh now.
