### ISSUE TITLE
Copy Qualifying Setup option

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#22]
Would be great to introduce a 'copy qualifying setup' option over in both the Dry and Wet feedback sections - this is a "nice to have" btw, but a good thing to include.

**Comment by JonBeagles** [comment]
This would copy the race setup from the last lap in qualifying over to whichever tab the "Copy Qualifying Setup" button was pressed on.  i.e. if it was pressed on the Wet Setup tab then the last qualifying lap gear/brake values would become the race wet setup (although could then be edited), and same if it was on the Dry Setup tab.  In theory they could copy it to both if they wanted...

**Comment by christopherh0rn** [comment]
Ah, I see, the "feedback sections" bit threw me.

Would it not make sense to let this be available for each lap of the qualifying session? So you would add two buttons to each lap on the Feedback tab that would copy that lap's values to the Race Setup's Dry/Wet tab (dependant on which of the two buttons was clicked).

Either way, if one has manually entered some values, would pressing this overwrite those values? Or would this functionality be disabled if any braking/gear values have been entered?

**Comment by JonBeagles** [comment]
If you like...though most people's best lap would be their final lap.  It would be rare their last lap is worse than a previous lap...but I'm happy either way.  Note that if you don't do it on every lap, that it should be on the final lap run and not on Lap 20 each time (i.e. if they only ran 6 laps, then Lap 6 would be copied over).

And yes it would overwrite any values in those cells.
