### ISSUE TITLE
UAT #3 - Wet Tyres on a Dry Qualifying Lap

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#25]
"Using wet tyres on a dry practice returns feedback of 'null' in the gear and brake entries for each corner when lap is submitted, if you move away and then go back to the feedback page then the 'null' entries are replaced with zeros rather than the settings that were placed in the fields.
(see practice lap 20, I ran the lap with valid figures for gears and braking and wet tyres)"

![image](https://user-images.githubusercontent.com/85413662/124433014-28759b00-dd6a-11eb-940f-e48928f6f6f4.png)

"Lap time with wet tyres was much slower, but not sure if this was the result of tyres or 'zero entries' for gear and brakes (system will not allow 0 gear entries to be submitted, but were shown in feedback form)"

This one is clearly a concern - not sure why that would be happening...?

**Comment by christopherh0rn** [comment]
The picture really helped btw. Just for future reference!

**Comment by JonBeagles** [comment]
Yep actually asked another UAT guy to send a picture of something else he has raised :)
