### ISSUE TITLE
Fuel use/tyre wear issue

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#3]
Lap 1 is showing as having 0 fuel use or tyre wear? The Lap 2 fuel/tyres look VERY low...I thought I had put in a normal amount, but I can't work out how to see what I put in there - that would be useful in future to be able to go back and see what parameters I had included. I don't think I would have used something so low though, so can you check that is calculating correctly please?

Certainly Lap 1 needs fixing at very least here.

**Comment by christopherh0rn** [comment]
So, I think that I may have misunderstood cell J1 in your F1 Revisited Master Sheet, so we were returning 0 fuel and tire wear after lap 1. If this is the issue then this will actually be a super easy fix as I was deducting 1 from the current lap number to get the laps already done (so when submitting lap 1, we were looking at the values for lap 0, it felt like it made sense at the time).
Do the values look like they might be consistent with being displaced by 1?

For the qualifying session on the staging server, you put the tyre wear as 3 and the fuel consumption as 1.5 (and the temperature as 35). I'll open up a new ticket regarding being able to see these bits of info.

Also, just a note to say that when I'd originally written this section, I put in unit tests that check that the fuel used and tyre wear for a qualifying lap matched what was coming out of the sheets after 1, 10 and 20 laps. I think these may have been all displaced by 1 so will correct the values accordingly in the tests.

**Comment by JonBeagles** [comment]
I can't see the totals per lap now (the session has now finished - so that's good at least) - but can you show me what the fuel/tyre totals were per lap for e.g. the first 3-5 laps or so (i.e. show me Lap 1 totals for both, Lap 2 totals for both etc. etc.)?

If my memory serves they weren't correct though, even with a 1 lap displacement (feel like one of them was e.g. 0.033 - which is clearly WAY too low...).

**Comment by christopherh0rn** [comment]
Ohhhhhhh, I know the issue. In the google sheets, the player format that as a percentage, so 1.0 would be 100% and 0.033 is 3.3% so it is displayed off by a factor of 100. Another easy fix, spent far too long looking at the master sheet!

Lap Number | Tyre Wear | Fuel Used
------------ | ----------- | ----------
1 | 0 | 0
2 | 0.05 | 2.25
3 | 0.08 | 3.75
4 | 0.11 | 5.25
5 | 0.14 | 6.75

**Comment by JonBeagles** [comment]
Yep that makes loads of sense mate :)

Fuel is correct there (albeit 1 lap out), tyres are indeed the %s as you say so just need to show differently.

**Comment by JonBeagles** [comment]
%s still not showing for this...
