### ISSUE TITLE
Race Setup Submission bug

### ISSUE THREAD

**Issue by christopherh0rn** [christopherh0rn/f1-revisited-bugs#30]
""Having filled in the Dry, Wet and Pit Stops tabs I cannot submit race setup.
When I try I get a "Please submit a complete race setup for at least one weather" error message."

"I went back through the race sheet and submitted successfully this time, not sure why it worked this time?

Once you log out and then back in the race setup info is not retained/shown to the manager so you cannot see what was submitted. None of the dry or wet setups, or the stint info is shown on the Race Setup page tabs."

Intriguingly going back out and back in did allow for a race submission - and without any prompting they also agree with wanting a 'Submitted' type message FYI. Retaining what info was submitted would also be great to have.

**Comment by christopherh0rn** [comment]
I could not reproduce this at all. Perhaps if it occurs again, a list of the values attempted to be submitted could be passed along?

Also, the information definitely _should_ be retained between logins and is in my testing.

Also also, by 

> shown to the manager

does that mean shown the player submitting the qualifying lap?

**Comment by JonBeagles** [comment]
Ah ok - and yes that means show to the player submitting the qualifying lap.

**Comment by christopherh0rn** [comment]
Closing for now. If this can be reproduced by anyone, if they can post the data they tried to use that would be very helpful!

**Comment by JonBeagles** [comment]
I have now asked for screenshots and specific values entered alongside the UAT feedback.

**Comment by christopherh0rn** [comment]
Got it, it wasn't registering braking values of 0.
