### ISSUE TITLE
UAT #7 - Qualifying Lap Total Inconsistency

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#32]
"I've done one lap. If I go out of the qualifying session, and view the leaderboard, it's showing me as having done 5 laps and having no time left.

If I go back into the qualifying session, all seems good again - my sheets are recording me as having done one lap, and having plenty of time left."

Checked and this is a definite bug:

https://drive.google.com/file/d/15gvG6tMUdZW6yFXgfh3G0I3wyMT3P169/view

Versus...

![image](https://user-images.githubusercontent.com/85413662/124672373-d5593080-deae-11eb-864b-e490fae7045f.png)

**Comment by JonBeagles** [comment]
This is Test Driver 1 btw.

**Comment by christopherh0rn** [comment]
This was looking at the total number of laps ever submitted by that driver rather than during that specific qualifying session. Fix is on its way out.
