### ISSUE TITLE
Warning messages on Race setup submission

### ISSUE THREAD

**Issue by christopherh0rn** [christopherh0rn/f1-revisited-bugs#35]
Put out a warning message if one isn't filled out that says "You have not put in any values for a Dry/Wet setup. This means if the weather is Dry/Wet that you will crash out of the race." Clearly, delete Dry/Wet according to what has/hasn't been included and I've said "crash out of the race" but I can't actually remember what we said would happen in that instance! If it's just losing loads of time then change it to be accurate please :)
Starting Fuel Amount (Minimum should be 10 litres - maximum should be 180 litres)

It would be good to add a message to say "You have not added any pit-stops yet - if you run out of fuel/tyres, you will lose a huge amount of time on track!" or words to that effect.

NB don't do this on validation as it would prevent ever being able to submit with missing values.

**Comment by JonBeagles** [comment]
All sounds like good ideas to me :)
