### ISSUE TITLE
UAT #8 - Missing Lap 7...

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#36]
"Seven is my unlucky number, so I decided to skip straight to lap 8...

https://drive.google.com/file/d/1A_nYwKHimh3OXaczR6EitWqNoaCbpO6p/view

Caused by opening two separate tabs, and running laps on both (in this example, after six laps I opened two tabs, ran lap 7 on one tab and lap 8 on the other). After exiting the quali session and going back in lap 7 and 8 both reappear together and all seems to work normally."

Not sure it's a huge issue this one - as it clearly corrected itself once he exited and went back in...albeit clearly not ideal that it happened.

**Comment by christopherh0rn** [comment]
This would be a fair bit of work to sort what is a fairly edge case. Nothing actually bad happened here, they weren't able to submit more laps than the maximum so going to set as won't fix.
