### ISSUE TITLE
Race Setup confirmation alert

### ISSUE THREAD

**Issue by christopherh0rn** [christopherh0rn/f1-revisited-bugs#39]
Not obvious when the player presses 'Submit Race Setup' that it has actually been submitted? Would be good if it could display a message that says "Race Setup now submitted" when they click submit (presuming it's successful).

**Comment by JonBeagles** [comment]
This is 100% needed, as Driver 3 tried to submit a race setup - got no confirmation and ultimately no setup was put in place.
