### ISSUE TITLE
UAT #11 - Missing Image

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#40]
https://imgur.com/a/NEwD7ng

"- the image has gone missing and refreshing the page does not bring it back."

I think this may be an issue around e.g. his cache...but just checking it's not something on our end!

**Comment by christopherh0rn** [comment]
If they could right click on the image and copy the URL that it's trying to load that would be really helpful, thanks.

**Comment by JonBeagles** [comment]
Asking now :)

**Comment by christopherh0rn** [comment]
Thanks!

**Comment by JonBeagles** [comment]
https://imgur.com/a/pBcAnw4

Also shows no track image FYI!

**Comment by JonBeagles** [comment]
He tried it on a different browser and the same issue, but this time it shows that there is an image (but still doesn't load it):

https://imgur.com/a/B0P9XuJ

**Comment by JonBeagles** [comment]
This is what it is trying to load up:

https://staging.f1revisited.co.uk/storage/track-images/Qw5dHleJ2seK934xhtZz3iEWHeU1BcYkkdni16hQ.jpg

(Says 404 not found for me also FYI)

**Comment by christopherh0rn** [comment]
That did not resolved the issue (but I do know what it is) and has in fact removed the track image that you added to each qualifying session.

**Comment by christopherh0rn** [comment]
Reinstated a track layout image of Sebring and this should now be sorted going forward.
