### ISSUE TITLE
UAT #12 - Edit Strategy after submitting

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#41]
https://imgur.com/a/fQqV5gh

"- when you submit a race setup, there is no way to go and edit it (before the race) in case you got something wrong. i think if you leave that closed, you should put a warning sign up at least, but it should preferably be editable till race start."

I do agree with this - if possible to allow strategies (plus Dry & Wet Setups) to be edited by clicking an 'Edit Strategy' type button up to when the race starts, that would be ideal :)

**Comment by JonBeagles** [comment]
"Once the race data has been submitted it is locked and there is no possibility to amend the submitted settings, I believe that it is essential to be able to make changes."

Again - an Edit Strategy type button would be a good solution to this.  Do like that it is locked down SOMEWHAT after submitting (i.e. it's clear and obvious it's submitted based on the fact that you can't just click on the cells to edit), but still they need the possibility to amend their strategy/setup until the race is run.

**Comment by JonBeagles** [comment]
"Also saved a Race Setup. After that, I couldn't edit it anymore. Is that intended? Because if it is, a heads-up warning would be nice that any input is final there.

Correction - After reloading the tab I can edit the race setup again.

If you do edit that race setup again though, it will delete your pit stop strategy! First thing I sent was a 2-Stop Strat with Stop Number 1 at Lap 14 and Number 2 at Lap 28. After editing the setup again, it deleted the pit strategy and only kept Stop Number 1 at Lap 14

And now I can't edit the strategy even after reloading"

**Comment by christopherh0rn** [comment]
I haven't been able to reproduce the editing the race setup after submitting it successfully issue. The intended behaviour is currently to prevent any editing after submission.

Even if I could reproduce it though, given that it seems that being able to edit already submitted race setups is potential work to be done in future, it isn't necessarily worth "fixing" that this person was able edit it on refresh now.

**Comment by JonBeagles** [comment]
They should be able to edit after submission though?  It's important they are able to do that...

Up until the time I actually run the race ideally.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
