### ISSUE TITLE
UAT #13 - Running laps with ANY settings undriveable

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#42]
"However, when trying to run a lap with 5/0 all across all 4 Turns, nothing happens. I press the button "Drive Lap", but apparently that just a picture, not something I can press.

To expand on my message from last night, after trying to change weather, track, get perfect setup etc I tried entering negative gear values / gear values above 6 and received these messages "The choice of gear for the Turn 1 must be between 1 and 5.". Then I tried to enter braking distances with lots of 0's and then also negative braking distances to get these messages "The amount of braking for the Turn 2 must be between 0 and 999.".

While all of this is perfectly fine and working as it should, after doing this, when I press "Drive Lap" with any correct setting, it doesn't do anything for me. It removes the error messages (since there is no wrong braking distance / gear choice), but the script doesn't seem to run past that error handler.

I am not sure if it worked before since I didn't run a lap prior.  "

Think you mentioned something about this before - but certainly he should be able to drive a lap!  Asked for a screenshot now FYI...

**Comment by JonBeagles** [comment]
https://imgur.com/a/pBcAnw4

(The 4th corner is also 5/0 - I checked)

**Comment by JonBeagles** [comment]
He tried it on a different browser and the same issue, but this time it shows that there is an image (but still doesn't load it):

https://imgur.com/a/B0P9XuJ

**Comment by JonBeagles** [comment]
This is a bigger problem in fact...ANY SETTINGS will not allow him to drive a lap.

Can you look at this one as a priority please mate?  Ideally before the quali session ends tomorrow...he is Test Driver 5.

**Comment by JonBeagles** [comment]
Same issue for a different tester (Test Driver #6) - who recorded a video about it:

https://www.facebook.com/messenger_media/?thread_id=1499798444&attachment_id=527924051783753&message_id=mid.%24cAAAAAEmO4hOA9lgBAl6xRISDV2su

Win10
Chrome.

**Comment by JonBeagles** [comment]
Alternative video link - https://youtu.be/T9F7y7GuSrU

**Comment by JonBeagles** [comment]
And another video - this time from Tester #5 (same guy as couldn't run laps originally), who again cannot run a single lap:

https://drive.google.com/file/d/1o5Dzb7KLsWIagwEfFSwXLrXShtpgt_-M/view

**Comment by christopherh0rn** [comment]
They should now be able to run laps. The database was missing the details for a levels 7 and 8 mechanics which the level 7 correlated with the number of pit crew that the team that both the testers who couldn't submit laps were in. Should now be resolved.
