### ISSUE TITLE
Running Race Issue

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#43]
So it looks like when I try to run the race, only 1 driver pulls through:

![image](https://user-images.githubusercontent.com/85413662/126164437-a854e936-7b97-4f23-bba5-79904c33139b.png)

Even though there are 3 qualified drivers?

![image](https://user-images.githubusercontent.com/85413662/126164543-502347ce-21fe-460c-a04c-4bad2c4f4e41.png)

Can you check why the other 2 are not showing up?  Guessing they have missed something in their driver setups?

After that, would be awesome if I could give you some values to replace what they have missed - that will to allow me to simulate the race with the 3 qualifiers and check that everything is working as it should.

**Comment by christopherh0rn** [comment]
Only 1 submitted a race setup, let me know what values you want inserting and I'll put them in the db.

**Comment by JonBeagles** [comment]
So 1 did (Tester 4), 1 didn't (Tester 1), but Tester 3 sent me this a few days back:

"Hi Jon,
Out of curiosity are you able to see the race setup that I submitted? Is the system saving it when submitted?
When I look at my Race Setup tab it is as if nothing has been submitted."

He's an experienced and reliable player - so seems odd to me that he wouldn't have just clicked 'Submit Race Setup'.  Will raise in a separate thread, but would be great to actually see who has/hasn't submitted their race setup as yet.

**Comment by JonBeagles** [comment]
As for race setups - use the same dry setups for each driver as their 20th dry lap.  In terms of fuel for Driver 1 just go for 60/60/60/60 and risk 4 through the race, as for Pit Laps I'd like the same 1st stop as Driver 4 and then the other stops on evenly spaced laps (roughly).  For Driver 3 65/65/65/65, risk 3 through the race and for Pit Laps I'd like the same 2nd stop as Driver 4 and the other stops on evenly spaced laps (roughly).

Let me know if that doesn't make sense...

**Comment by christopherh0rn** [comment]
Now 3 drivers ready, have added pit stops and cornering choices as requested.
