### ISSUE TITLE
UAT #14 - Base Lap time too large

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#45]
"Qualify process seems basically okay, though I suspect that the laptime is much longer than intended.
Despite zero pit time I have run out of testing time after only 8 laps, the lap time is around 504 seconds whereas S59 lap times were around 181 seconds."

Not sure why the base lap-time is so long on Sebring?  Unless I've sent you over a document with a typo at some point...either that or there's some other reason the lap-time is so long!  Can you investigate please?

Would be helpful to see (and be able to amend) the base lap-time when I create a new Qualifying Session btw - or have some kind of track amendment option...

**Comment by christopherh0rn** [comment]
The base lap time for Sebring is down as 505, as it is in the original F1R - the Database you sent over. Can see in subsequent emails that changed to 185, shall I update accordingly?

I'll create a separate issue with the track editing feature request.

**Comment by JonBeagles** [comment]
Unless that will change the lap-times already run, just leave as is for now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JonBeagles** [comment]
Think this one can be closed btw?

**Comment by christopherh0rn** [comment]
Did you not want the base lap time at Sebring updating from 505 to 185?

**Comment by JonBeagles** [comment]
Sebring doesn't appear on the F1 calendar again mate (last time was in 1959) :)
