### ISSUE TITLE
Running Race Issue

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#50]
Not sure why there's an internal server error when I try to run the race?

![image](https://user-images.githubusercontent.com/85413662/126901435-22714d3f-2736-4103-ac47-abc6d29060a5.png)

**Comment by christopherh0rn** [comment]
Try again now.

**Comment by JonBeagles** [comment]
Same result - logged in and out twice, still the same result as the above image.

**Comment by christopherh0rn** [comment]
To confirm, this is a totally separate problem under the hood. Working on a fix now.
