### ISSUE TITLE
Dark Blue Feedback

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#58]
Can we take the darkest blue feedback colour and make it a little lighter, so the text is easier to see.  If that causes issues then I'd also be fine with changing the colour of the writing to white against the dark blue background.

**Comment by christopherh0rn** [comment]
I'm slightly confused by this as I never got round to updating this yet this is what the slow feedback currently looks like:


<img width="231" alt="Screenshot 2021-11-02 at 20 45 19" src="https://user-images.githubusercontent.com/13766234/139949233-e8bf4efc-fe43-4d41-b8f0-3fa00990d0bc.png">
<img width="176" alt="Screenshot 2021-11-02 at 20 48 18" src="https://user-images.githubusercontent.com/13766234/139949525-a130a164-68cd-4a88-9eb9-012546ad12ce.png">
<img width="195" alt="Screenshot 2021-11-02 at 20 48 24" src="https://user-images.githubusercontent.com/13766234/139949498-e8c9b63e-132e-473f-a0d3-eb1f3abe2b60.png">

**Comment by christopherh0rn** [comment]
Ah, ignore me. Will resolve this now.

<img width="182" alt="Screenshot 2021-11-02 at 20 54 46" src="https://user-images.githubusercontent.com/13766234/139950226-63e03108-1a59-41b5-b84c-3bdaa4791315.png">
