### ISSUE TITLE
URGENT - Player trying to submit race setup can't...

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#64]
"Jon, was a bit confused when you said i hadnt entered a setup (which i had), so i checked and it wasnt there... - go figure...

anyway, tried to enter it again and got this error:

There was an error submitting your race setup, please try again later. If this is recurring, please contact Jon.
The error was: undefined - CSRF token mismatch."

![image](https://user-images.githubusercontent.com/85413662/136634314-0a32869b-6348-4165-8e2b-fe9bad768c88.png)

Any ideas why?  Is there a space before the starting fuel number maybe...?

**Comment by JonBeagles** [comment]
2 players now stating the same issue...

**Comment by christopherh0rn** [comment]
That just means their session token has expired. They should be able to refresh the page and it work as expected.

We can look to expand on this and prevent this from occurring with some future work.

**Comment by JonBeagles** [comment]
Cool please include this in the quote for the next set of work mate :)
