### ISSUE TITLE
Driver/car images

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#7]
Would be epic if I could assign images to each player for e.g. the driver/car they are in that showed up somewhere in qualifying (in the space at the left or right hand side of the screen perhaps).

**Comment by JonBeagles** [comment]
For this one, if you could add a 'Car Image' option on the Teams section for me to upload that would be a great start.

Then, if that car image could show up on the Qualifying screen wherever there's space that would be great.  For the driver option, it would be great when setting up the drivers if I could also upload an image of them and have that show up again in qualifying (next to the car ideally).

Car image more important than the Driver image FYI - and in future I may want to look at having that car image appearing within the race page...but that one can be parked for the future (will raise that as a new issue when the time comes).

**Comment by christopherh0rn** [comment]
Which page exactly would you like the team's car image displayed?

- On the screen where a driver enters their individual qualifying lap setups
- One for each driver on the overall qualifying page, such as this one https://staging.f1revisited.co.uk/qualifyingsessions/gdY3cuBR07D4Mp3jWAGbJv0tS7dhXDMp
