### ISSUE TITLE
Joakim Bonnier refuelling

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#74]
Hi mate,

Joakim Bonnier pits on both Lap 78 and Lap 80 - the guy swears blind that he didn't put that in his race instructions.

Can you check and - if it's not too difficult - remove the lap 80 pit please?

**Comment by JonBeagles** [comment]
Also possibility this could be a bug, as the players swears he removed that stop...can you check and see that it will allow players to remove stops and not keep the pit-lap in place please?

**Comment by christopherh0rn** [comment]
So this is what is there:

Stop number | lap number | fuel| risk | created datetime | update datetime
---|---|---|---|---|---
1|26|51|2|2021-10-08 16:27:08|2021-10-09 16:01:28
2|52|51|2|2021-10-08 16:27:08|2021-10-09 16:01:28
3|78|43|3|2021-10-08 16:27:08|2021-10-09 16:01:28
4|80|42|3|2021-10-08 16:27:08|2021-10-08 16:27:08

**Comment by christopherh0rn** [comment]
Can easily remove the 4th stop and will investigate whether this could be a bug.

**Comment by JonBeagles** [comment]
Perfect - thanks mate :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Was a bug. Bugfix merging in now. Rogue pitstop already deleted from the database 👍

**Comment by JonBeagles** [comment]
Awesome - let me know when I'm good to do the rerun...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Rogue pitstop already deleted and bugfix preventing extraneous pitstops merged and deployed.

The fix means that in future, if they submit 5 pitstops and then decide to go down to 3, the redundant 4th and 5th ones will now be removed.

**Comment by JonBeagles** [comment]
Awesome cheers mate :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
