### ISSUE TITLE
Drive Lap Button not working

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#75]
Session is setup correctly, session has definitely started, all boxes have a value in them.

When we press 'Drive Lap' it clearly registers it (the button briefly disappears and is replaced by the loading circle) - but the lap is not driven?  There is no Feedback on the feedback tab, it does not advance to Lap 2 and there are no error messages whatsoever anywhere on the page.

Tried logging in and out a couple of times, but it's always the same result :(

**Comment by christopherh0rn** [comment]
It's because her lap time is greater than the value allowed in the column (she's just too slow!!!!). I'll add a migration to give an order of magnitude or two of redundancy so we don't run into this issue again.

**Comment by JonBeagles** [comment]
Haha nice one mate - I tried it originally with a setup that would have been reasonably accurate FYI, so it's a good job we caught this!

Let me know once that fix is deployed if you would :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Just ran a test lap on staging with first gear for every corner and 1 braking and it ran successfully, deploying to main site now.

**Comment by JonBeagles** [comment]
Nice one mate :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
That should now be deployed.
