### ISSUE TITLE
Pit-Stop Issue

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#77]
Joakim Bonnier only did 1 pit-stop on Lap 24 - but according to his Race Setup page he did the following 3 stops:

https://imgur.com/RIbcgE0

Von Trips had a similar issue - but waiting for his screenshot still to confirm.

**Comment by JonBeagles** [comment]
Also did 1 stop on lap 24 - and yet put in the following:

https://imgur.com/Y4dJ45d

**Comment by christopherh0rn** [comment]
This is from stale caching with legacy cache keys used. I've cleared the cache and am just amending the cache keys to ensure that we don't ever get conflicts again.

Technically you could re-run the race now but I'd wait about 10 mins for me to finish this 👍

**Comment by christopherh0rn** [comment]
That's now deployed.

**Comment by JonBeagles** [comment]
Nice one mate - will re-run this evening.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Is this now working as anticipated?

**Comment by JonBeagles** [comment]
Yes it worked fine :)
