### ISSUE TITLE
Issue submitting race setup

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#78]
Hi Jon

It won't let me submit race setup, comes up with the error message "There was an error submitting your race setup, please try again later. If this is recurring, please contact Jon.

The error was: undefined - CSRF token mismatch."

I've tried a few times.

Cheers

That was from Finn Shaw-McIver, who plays as Willy Mairesse FYI.

**Comment by christopherh0rn** [comment]
I think they just need to refresh the page. They've been logged out. We encountered this before and it's on the to-do list for future work. If it doesn't work after page refresh let me know.

**Comment by christopherh0rn** [comment]
This being the related issue: https://github.com/christopherh0rn/f1-revisited-bugs/issues/69
