### ISSUE TITLE
Closest to Perfect Setups - calculating on which lap-time?

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#79]
Can you confirm whether closest to perfect are calculating off qualifying best lap or on race setup submission please?

Qualifying best lap is what I want the players to see, but I need to be able to download the closest to perfect in the race setup submitted.  Not sure we have that right now?

**Comment by JonBeagles** [comment]
FYI fine for the players to see the qualifying one - but I'd love to have a button that allows me to export the closest to perfect for Race Setup

**Comment by christopherh0rn** [comment]
So this is currently calculated from the qualifying lap that has just been ran.

It's calculated as the total quick time loss plus the total slow time loss.

I don't think this will be trivial to calculate as one would essentially have to do a dry run of a lap to get the time with the race setup. You'd also need to know what sort of weather the race was going to have which we don't know at this stage.

**Comment by JonBeagles** [comment]
Surely for the race pace we are already calculating quick and slow time loss though? So the numbers should already be there to extract the same totals from...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JonBeagles** [comment]
To be clear, I am looking for the same calculation that is done right now - i.e. qualifying weather vs lap inputs. Only difference is I want it to use the lap inputs from the race setup and not from the last quali lap.

Just a reminder that you can keep what the players see as the same - but I need a separate list of who is closest with their race setup that I can see and/or extract.

Fine if that costs extra to achieve btw.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
This is definitely new functionality I'm afraid. Shouldn't be as complex as I first thought but still not the most straight forward of things.

**Comment by JonBeagles** [comment]
Ok we need this for the season to start, as I need to pay bonuses for this Indy 500 race based off the race setup performance.

If you can implement that (fine if there's a cost) this week then please can we do that ASAP. If not this week, when is likely do you reckon?

If you can't add it this week, can you do me a 1-off extract of the dry race setups submitted by each driver (just gears and braking points for the 4 corners) and I can try to calculate it manually instead.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Possibly this week but I wouldn't want to commit without knowing what other stuff will need to be done on the other tickets that might take priority.

Definitely happy to commit to provide you the extract of the dry race setups submitted this week though.

After this week, I may have a little time the week of the 28th of February as well as the odd hour here and there before then.

**Comment by JonBeagles** [comment]
Extract is fine for this week - but it would need to be a extract every race (about once every 2 weeks) until the real thing was in FYI.

So if it was 28th Feb then there would likely be 1 more extract to do before then.

The only thing that's a higher priority than this is Rodriguez pace issue FYI.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
I'll try and get that done this week as I can guarantee I'm unlikely to have availability to do that big export once a fortnight or so after this current week.

I'll whatsapp you directly with a quote for this at some point today.

**Comment by JonBeagles** [comment]
Nice one mate - cheers

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Here is the export:

Race Setup for Tony Brooks
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6485703550000000
Gear: 5

Turn 3:
Brake: 17.4614345680000000
Gear: 4

Turn 4:
Brake: 0.3701439100000000
Gear: 5

---
Race Setup for Dan Gurney
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6486033400000000
Gear: 5

Turn 3:
Brake: 17.4624037400000000
Gear: 4

Turn 4:
Brake: 0.2993576700000000
Gear: 5

---
Race Setup for Willy Mairesse
Turn 1:
Brake: 0.0000000000000000
Gear: 6

Turn 2:
Brake: 0.6987266100000000
Gear: 6

Turn 3:
Brake: 18.4663458500000000
Gear: 5

Turn 4:
Brake: 0.3992715000000000
Gear: 6

---
Race Setup for Joakim Bonnier
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6485245000000000
Gear: 5

Turn 3:
Brake: 17.4602700000000000
Gear: 4

Turn 4:
Brake: 0.2993168000000000
Gear: 5

---
Race Setup for Giancarlo Baghetti
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6460000000000000
Gear: 5

Turn 3:
Brake: 17.4724200000000000
Gear: 4

Turn 4:
Brake: 0.2986000000000000
Gear: 5

---
Race Setup for Wolfgang von Trips
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6483610687250000
Gear: 5

Turn 3:
Brake: 17.4560156250000000
Gear: 4

Turn 4:
Brake: 0.2997070312500000
Gear: 5

---
Race Setup for Brian Naylor
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6486207780000000
Gear: 5

Turn 3:
Brake: 17.4629257900000000
Gear: 4

Turn 4:
Brake: 0.2991015630000000
Gear: 5

---
Race Setup for Nino Vaccarella
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6489153125000000
Gear: 5

Turn 3:
Brake: 6.7000000000000000
Gear: 3

Turn 4:
Brake: 5.0999968750000000
Gear: 5

---
Race Setup for Roy Salvadori
Turn 1:
Brake: 0.0000000000000000
Gear: 6

Turn 2:
Brake: 0.6979890190000000
Gear: 6

Turn 3:
Brake: 18.4468526450000000
Gear: 5

Turn 4:
Brake: 0.3988510000000000
Gear: 6

---
Race Setup for Edgar Barth
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6489153125000000
Gear: 5

Turn 3:
Brake: 17.4707968522000000
Gear: 4

Turn 4:
Brake: 0.2999984380000000
Gear: 5

---
Race Setup for Carel Godin de Beaufort
Turn 1:
Brake: 0.0000000000000000
Gear: 6

Turn 2:
Brake: 0.6984463000000000
Gear: 6

Turn 3:
Brake: 18.4588843650000000
Gear: 5

Turn 4:
Brake: 0.3995254200000000
Gear: 6

---
Race Setup for Jack Fairman
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6489152526855480
Gear: 5

Turn 3:
Brake: 17.4505362701415000
Gear: 4

Turn 4:
Brake: 0.3047318267822250
Gear: 5

---
Race Setup for Tony Maggs
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6489153125000000
Gear: 5

Turn 3:
Brake: 17.4708593800000000
Gear: 4

Turn 4:
Brake: 0.2999984468000000
Gear: 5

---
Race Setup for John Surtees
Turn 1:
Brake: 0.0000000000000000
Gear: 6

Turn 2:
Brake: 0.6987266000000000
Gear: 6

Turn 3:
Brake: 18.4663457000000000
Gear: 5

Turn 4:
Brake: 0.3992497000000000
Gear: 6

---
Race Setup for Tony Marsh
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6521601000000000
Gear: 5

Turn 3:
Brake: 17.4527508000000000
Gear: 4

Turn 4:
Brake: 0.3891162000000000
Gear: 5

---
Race Setup for Stirling Moss
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6483700000000000
Gear: 5

Turn 3:
Brake: 17.1055000000000000
Gear: 4

Turn 4:
Brake: 0.5235000000000000
Gear: 5

---
Race Setup for Phil Hill
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6541250000000000
Gear: 5

Turn 3:
Brake: 17.4526700000000000
Gear: 4

Turn 4:
Brake: 0.2924600000000000
Gear: 5

---
Race Setup for Maurice Trintignant
Turn 1:
Brake: 0.0000000000000000
Gear: 6

Turn 2:
Brake: 0.6983168500000000
Gear: 6

Turn 3:
Brake: 18.4693457000000000
Gear: 5

Turn 4:
Brake: 0.3971997000000000
Gear: 6

---
Race Setup for Ricardo Rodríguez
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.5411229492000000
Gear: 5

Turn 3:
Brake: 14.5685885100000000
Gear: 4

Turn 4:
Brake: 0.2497557455000000
Gear: 5

---
Race Setup for Keith Greene
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6487632441000000
Gear: 5

Turn 3:
Brake: 17.4667026367180000
Gear: 4

Turn 4:
Brake: 0.3025001525878000
Gear: 5

---
Race Setup for Lorenzo Bandini
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6489153125000000
Gear: 5

Turn 3:
Brake: 17.4707968903000000
Gear: 4

Turn 4:
Brake: 0.2999984360000000
Gear: 5

---
Race Setup for Cliff Allison
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6487306400000000
Gear: 5

Turn 3:
Brake: 17.4658251200000000
Gear: 4

Turn 4:
Brake: 0.2994148200000000
Gear: 5

---
Race Setup for Graham Hill
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6559250000000000
Gear: 5

Turn 3:
Brake: 17.4386700000000000
Gear: 4

Turn 4:
Brake: 0.2924600000000000
Gear: 5

---
Race Setup for Innes Ireland
Turn 1:
Brake: 0.0000000000000000
Gear: 6

Turn 2:
Brake: 0.6986337500000000
Gear: 6

Turn 3:
Brake: 18.4638850000000000
Gear: 5

Turn 4:
Brake: 0.3979999990000000
Gear: 6

---
Race Setup for Jim Clark
Turn 1:
Brake: 0.0000000000000000
Gear: 6

Turn 2:
Brake: 0.6987165500000000
Gear: 6

Turn 3:
Brake: 18.4660102500000000
Gear: 5

Turn 4:
Brake: 0.3992101000000000
Gear: 6

---
Race Setup for Masten Gregory
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6559250000000000
Gear: 5

Turn 3:
Brake: 17.4386700000000000
Gear: 4

Turn 4:
Brake: 0.2924600000000000
Gear: 5

---
Race Setup for Lucien Bianchi
Turn 1:
Brake: 0.0000000000000000
Gear: 5

Turn 2:
Brake: 0.6485955537800000
Gear: 5

Turn 3:
Brake: 17.4661527357000000
Gear: 4

Turn 4:
Brake: 0.2822157530000000
Gear: 5

**Comment by JonBeagles** [comment]
Thanks :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
I've added this to the race setups submitted table.

I'm pretty sure there are some edge cases that I've missed.

For testing this, I've set every user to have your password on the staging site and I'll make the latest qualifying session at Indy still be in progress to help you test this before merging it into production.

**Comment by christopherh0rn** [comment]
Also, just to say, it generates the how far from perfect for the race setup at the point that the race setup is submitted so unless you re-submit each of the drivers race setups in the Indy qualifying, it's default to displaying 0. I've re-submitted Masten Gregory's hence it showing you what his is.

**Comment by JonBeagles** [comment]
Nice one mate - will try and test this afternoon :) that said, ideally would like to wait until you implement the multiplier fix and test it all together :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
