### ISSUE TITLE
Multipliers

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#82]
Hi mate,

Just had a moment of panic - hoping you can set my mind at ease.  Either that or you are likely to need to quote me for an addition to the site.

There should be 2 multipliers for a driver...1 is the base multiplier (that is based on the amount of races they have done and increases by 0.01 for every race they do - that is what the stamina calculation works from), the other is the race multiplier (that is the base multiplier + the multiplier boosts they have purchased).

All of that means those with higher multipliers aren't just automatically disadvantaged by it and can purchase boosts to offset the stamina impact.

I'm worried that we may just have 1 multiplier value - the one I asssign on the Driver page, which is working as the base multiplier.  When actually we need 2 values - 1 for the base multiplier (only used for the stamina calculation) and 1 for the race multiplier (used for everything else involving the multiplier).

If you can't set my mind at ease that there are 2 different multipliers on the site, then the following changes need to happen:

1 - Add a Base Multiplier field to the Drivers tab for each driver (change the name of the other field to Race Multiplier for each driver)
2 - Change the formula involving stamina to calculate from the new Base Multiplier field

All other formulae can then just stay the same, as all but stamina should point at the current field that's there.

Let me know likely cost and timescales please?  Assuming this doesn't exist already...

**Comment by JonBeagles** [comment]
@christopherh0rn when do you reckon you'll be able to look at this next?

**Comment by christopherh0rn** [comment]
So within the codebase we have the concept of two different multipliers, one is called the contract multiplier, the other just called multiplier.

The multiplier is stored against each driver but also stored when they enter a race, that way you can see what their multiplier is at a point in time (like when they enter a race) as well as what it is currently.

Currently in the Drivers settings page, if one changes the Multiplier, it sets both the multiplier and the contract multiplier to the same thing.

When one sets up a new race, one can set a base multiplier. Again this updates both the multipliers (regular and contract).

When running a Race, the contract multiplier is used in the calculation for stamina effect. The multiplier is used for everything else.

Qualifying appears to only use the multiplier.

So in terms of how to proceed:
1) Agree the names of these two multipliers and where each should be used. It would be a pain to remove the contract terminology as that is used in several places in the codebase so I'd be quite keen if we could stick with that.

2) Be able to change the 2 different modifier values independently from the Driver's settings page?

3) Not set both when choosing a base multiplier value on the new race page

4) Does qualifying need to change its behaviour at all?

**Comment by JonBeagles** [comment]
So contract multiplier is only used for Stamina? That's behaving correctly if so (but that is what I would call the 'Base Multiplier' - fine to call it Contract though). Let's call the other one Race Multiplier for clarity.

You say "when one sets up a race"...that's only after qualifying though right? This option needs to be there pre-qualifying to add in the Race Multiplier at that stage. Contract Mutliplier is presumably the one I set on the Drivers page then right?

The Contract Mutliplier should NOT override the base multiplier (and vice versa - these are two separate numbers).

Great news that this already exists - we just need the two not to override each other and for me to be able to set the contract ones linked to a qualifying and race event (NB - the base and contract multipliers will both not change between the start of quali and the end of the race).

E.g. Baghetti has Contract Multiplier of 1.00 but buys (using game money) some upgrades and so generates a Race Mutliplier of 1.2. Stamina should calculate off the 1.00 value, while everything else should calculate off the 1.2.

Let me know how much money/time is needed to make this happen please?

Cheers,
Jon

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
Does this have to be from a screen pre-qualifying? Could adding a field in the drivers settings page for the race multiplier work so you'd set both the contract and race multiplier there?

**Comment by JonBeagles** [comment]
Yes it has to be pre-qualifying and yes adding a field in the Driver Setting page is the ideal solution :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by christopherh0rn** [comment]
These changes should now have been deployed to the staging site.
