### ISSUE TITLE
Staging Server -  can't run race?

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#83]
All values are in correctly to run a race at Riverside (for a fun tournament I'm running - but with 10 people waiting for a result!). everything looks fine but when I press 'Let's Race' it just comes up with the following almost immediately:

Internal Server Error, please email [chris@flagpolestudios.com](mailto:chris@flagpolestudios.com)

Is this because I have another qualifying session running simultaneously perhaps???  Need to resolve this ASAP, as I'm meant to be running 3 races during the month of March and it would be really embarassing if I can't run them...

**Comment by christopherh0rn** [comment]
I think this is a stale cache issue because it was trying to retrieve a cached driver (which we no longer cache) and retrieving a totally different person who isn't in this race. I have cleared the cache which should resolve this issue.

**Comment by JonBeagles** [comment]
Yep all fixed now :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
