### ISSUE TITLE
Invite emails not sending

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#87]
The invite email shows as being successfully sent from the main site - but no email ever comes through.  2 different email addresses for a player with 2 days and 1 day waiting respectively - also tested on Rach's alternate email and nothing has come through around 30 minutes later...?

Please investigate ASAP!

**Comment by christopherh0rn** [comment]
This was due to hardening of some security restrictions on the server. This has now been resolved. I will delete those 3 invited players (2 variations of a parmalatios email and Rach) so you can re-invite them without issue.

**Comment by JonBeagles** [comment]
Amazing - thanks mate :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JonBeagles** [comment]
This is sorted now btw :)
