### ISSUE TITLE
Problem with Mixed Race - Retired Drivers returning!

### ISSUE THREAD

**Issue by JonBeagles** [christopherh0rn/f1-revisited-bugs#89]
Up until Lap 25 of the 1961 Spa GP everything looks absolutely spot on - when, presumably because the rain has stopped, those who had retired without a wet setup earlier in the race suddenly become reinstated and appear about 6,000 seconds ahead of the leader!  After that point everything looks fine in terms of the others in the race - but clearly those 6 retired drivers need to stay retired and then all will work properly!

Can this be amended ASAP please, as this is holding up moving the season on...

**Comment by christopherh0rn** [comment]
Have tested on staging and this appears to be resolved. Will merge into main and deploy now.

**Comment by christopherh0rn** [comment]
That's now deployed to live successfully. Please let me know if this resolves the issue.
